### PR TITLE
[HOPSWORKS-2317] Remove featurestore module from hops-util-py and hops-util

### PR DESCRIPTION
**Pull request by moritzmeister**

### CODE REVIEW

**Review by robzor92 — COMMENTED** [review]
Did you try building the docs and check that all sections show up with content? Also would be good to do some basic tests for existing modules. Atleast importing and that some basic functionality still works.

**Comment by moritzmeister** [comment]
Hm I don't see anything about how to build documentation in the readme. I haven't done it in a long time. do you have the command?

I will install it and test that the other modules still work.

**Comment by robzor92** [comment]
Okay! :) Build instructions should be here: https://github.com/logicalclocks/hops-util-py/blob/master/Development.rst#documentation

**Comment by moritzmeister** [comment]
Tested building the docs, looked good, a lot of warnings while building it though. Tested importing the modules which could've had dependencies on the featurestore module.

**Review by robzor92 — APPROVED** [review]

**Pull request merged**
